### ISSUE TITLE
I cant understand your level of code!

### ISSUE THREAD

**Issue by praserocking** [shiv6146/DS-and-Algos-in-Python#1]
please , paamara people kum puriura madiri code eludhavum! :-P

**Comment by sivag123** [comment]
+1

**Comment by shiv6146** [comment]
Asingama kalaaipa la nee...
Ek din aatha hai...
Mai ooper jaatha hai...

**Comment by shiv6146** [comment]
dai na ipo than da start paniruken...
unga alavuku tree, graphs lam implement panama vida maten :-P

**Comment by praserocking** [comment]
THambi! visual recursion lam mass ah iruku! kalakku dude nee..;) close the issue.. idha poi namma chat maari use panrom..:-D
